### PR TITLE
Fix install issues

### PR DESCRIPTION
**Pull request by arodier**
Small fixes that stops the installation

### CODE REVIEW

**Comment by fredericmoulins** [comment]
Late, but:
```
Oct 1, 2020 the A record for api6.ipify.org will be removed to make the subdomain only for IPv6 requests. For universal access please use api64.ipify.org.
```
Cf "API Usage" in https://www.ipify.org/.

The `api6.ipify.org` only has `AAAA` records now and can be joined only with IPv6.

The `api64.ipify.org` should correspond to the previous usage.

**Comment by fredericmoulins** [comment]
From the dev branch with this change:
```diff
diff --git a/install/roles/remote-access/tasks/ufw-public-access.yml b/install/roles/remote-access/tasks/ufw-public-access.yml
index 958facfa..e4cee089 100644
--- a/install/roles/remote-access/tasks/ufw-public-access.yml
+++ b/install/roles/remote-access/tasks/ufw-public-access.yml
@@ -22,7 +22,7 @@
   delegate_to: localhost
   register: ext_ip6_api_response
   uri:
-    url: https://api6.ipify.org/
+    url: https://api64.ipify.org/
     return_content: true
 
 - name: Make sure the external IP address is working as well
```
I tested it behaves as before. The `api64` server has the same behavior as the former `api6` server.

How do you want to proceed: revert the commit in the PR, or rebase and replace with this change?

**Comment by arodier** [comment]
Replacing with this change seems OK to me.

**Comment by fredericmoulins** [comment]
Please see changes in #357.
The bullseye branch will have to be rebased.

**Comment by arodier** [comment]
I have rebased bullseye on dev, and pushed.

**Comment by arodier** [comment]
Not relevant any more

**Pull request closed without merging**
