### PR TITLE
Conditional installation of external ip check scripts

### PR DESCRIPTION
**Pull request by fredericmoulins**
Let the playbooks depend on the common/roles/external-ip-type to determine external_ip(_type) and backup_ip(_type).

Simplify the install/playbooks/roles/external-ip to only install the external-ip-check scripts.

Install the external-ip-check scripts only if network.auto_detect_ip is true.

Maybe the playbook and role "external-ip" could be renamed to something like "external-ip-check-scripts" (maybe a bit long :sweat_smile:) to avoid confusion with the common "external-ip-type" ?

### CODE REVIEW

**Comment by arodier** [comment]
Sorry, you lost on this one ;-)

Two things I cannot accept:

- The external_ip_type and backup_ip_type are absolutely necessary. I have servers with two IP addresses, one in IPv4 and one in IPv6. If you remove these variables, how the bind template will know to use A or AAAA record types for IP addresses?
- Using a file in /tmp to store the external IP address is better. It decreases deployment time, as you don't need to request every time an external service to get the IP address. And since the external ip address role is a dependency on multiple roles, this is not great.

Finally, I think we should have a quick talk (in French ?) about the IP detection address feature.

**Comment by fredericmoulins** [comment]
> Sorry, you lost on this one ;-)

:smile: 

> 
> Two things I cannot accept:
> 
>     * The external_ip_type and backup_ip_type are absolutely necessary. I have servers with two IP addresses, one in IPv4 and one in IPv6. If you remove these variables, how the bind template will know to use A or AAAA record types for IP addresses?

I agree. I need this, too.

The idea is to have one role setting the external_ip, external_ip_type, backup_ip, backup_ip_type facts during deployment, and another one installing the external-ip-check scripts on the server if needed (for dynamic/NATed configurations).

 The `common/roles/external-ip-type` role does set those facts. I tried to make sure it is done in the various roles that need it (85f7739).

The `install/playbooks/external-ip.yml` playbook installs the `external-ip-check` scripts on the server, and it was also detecting IP types. I tried to have it only do the installation on the server part (3fa6586). (And in fact, this playbook appears not to require the `external_ip` facts after [this change](https://github.com/progmaticltd/homebox/pull/199/commits/85f77398b6e34aeea11090ce3870f7f77bbd8a60#diff-f1efe54092e272212ede23bcb1093bfc).)

>     * Using a file in /tmp to store the external IP address is better. It decreases deployment time, as you don't need to request every time an external service to get the IP address. And since the external ip address role is a dependency on multiple roles, this is not great.

I realise now that the way I added `external-ip-type` as a dependency is far from efficient. The idea would be to have it behave like the `load-defaults` role: make sure it is loaded only once in any playbook run that needs it.

> Finally, I think we should have a quick talk (in French ?) about the IP detection address feature.

Yes we can (and yes, in French also).

I won't need the auto IP address detection in the near future, but I understand the need for it, and it is not an easy one.

Now, considering a static configuration (without auto-detection), I would like to be able to have dual-stack services. Something like:
```
main    IN    A       <ip4addr>
main    IN    AAAA    <ip6addr>
```
And potentally the same with `backup`. Like now, only one IP address required (v4 or v6), all others being optional.

So, yes, there are some things to talk about concerning the IP addresses.
(I will be off for a few days, but I might be able to receive emails).

**Comment by arodier** [comment]
I gradually changed my mind about the pertinence of automatic external IP address detection in self hosting.

- If you want to be self-hosted, you may already have a static IP address, and therefore knows it.
- If you don't have a static IP address, you cannot be self-hosted, but see below...

Moreover, the external IP address detection might detect the address used to communicate externally, but not the address configured behind a NAT.

So, the option I want to use is to provide static IP addresses to people with a dynamic one, using a simple VPN hosted online, for instance using [Vultr](https://www.vultr.com/). They are cheap 60$ per annum, provides both IPv4 and IPv6 addresses, and allow the usage of the port 25, not like DigitalOcean or google cloud. Part of their disk space could also be used as an off-site backup storage.

The idea is to create a simple method to quickly build a VPN server online (perhaps using Ansible Vultr API), and deploy the VPN client keys on HomeBox.

Once the key deployed and the VPN running, the HomeBox server has two static IP addresses, one IPv4 and one IPv6, and about 20Gb of storage for off-site backup.

To deploy the server, you need a Vultr API key, but I cannot provide the key to everyone, as I would be the one to pay, but there are options.

The first is to provide the API key as a variable. Those who are interested should register on Vultr and get an API key before getting their gateway server.

The second solution is to keep the Vultr API key ourselves, and to invoice people, but there are aspects behind this that need to be discussed.

By adding an external IP address to the SPF record, you are already going towards this kind of solution.

**Comment by arodier** [comment]
Frédéric, I am going to close this request. You can contact me by email or xmpp at andre@rodier.me, for a video call if you want.

**Pull request closed without merging**
