### PR TITLE
Fix dir backup urls examples

### PR DESCRIPTION
**Pull request by fredericmoulins**
Use dir:///var/backups/homebox for the location to be the absolute path
/var/backups/homebox when processed by backup.py.

### CODE REVIEW

**Comment by progmaticltd** [comment]
I don't think this is correct, the url is parsed using [ansible urlsplit](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#url-split-filter) filter, and the result is correct.
The double "//" after the protocol "dir" is necessary, otherwise, the location is wrong.

I just ran an example as I was not sure too.

```
TASK [system-prepare : Extract backup location details] ************************
task path: /home/andre/Projects/homebox/install/playbooks/roles/system-prepare/tasks/main.yml:3
ok: [homebox] => changed=false 
  ansible_facts:
    location:
      url: dir:///var/backup/test
Saturday 10 August 2019  15:30:17 +0100 (0:00:00.036)       0:00:06.294 ******* 

TASK [system-prepare : Extract backup location details] ************************
task path: /home/andre/Projects/homebox/install/playbooks/roles/system-prepare/tasks/main.yml:9
ok: [homebox] => changed=false 
  ansible_facts:
    location_details:
      fragment: ''
      hostname: null
      netloc: ''
      password: null
      path: /var/backup/test
      port: null
      query: ''
      scheme: dir
      username: null
    location_host: ''
    location_path: /var/backup/test
    location_user: ''
    protocol: dir
Saturday 10 August 2019  15:30:17 +0100 (0:00:00.087)       0:00:06.382 ******* 

TASK [system-prepare : Extract backup location details] ************************
task path: /home/andre/Projects/homebox/install/playbooks/roles/system-prepare/tasks/main.yml:18
ok: [homebox] => changed=false 
  ansible_facts:
    location:
      url: dir://var/backup/test
Saturday 10 August 2019  15:30:17 +0100 (0:00:00.080)       0:00:06.462 ******* 

TASK [system-prepare : Extract backup location details] ************************
task path: /home/andre/Projects/homebox/install/playbooks/roles/system-prepare/tasks/main.yml:24
ok: [homebox] => changed=false 
  ansible_facts:
    location_details:
      fragment: ''
      hostname: var
      netloc: var
      password: null
      path: /backup/test
      port: null
      query: ''
      scheme: dir
      username: null
    location_host: var
    location_path: /backup/test
    location_user: ''
    protocol: dir
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************
homebox                    : ok=34   changed=0    unreachable=0    failed=0   

 ```

**Comment by fredericmoulins** [comment]
I don't understand, your test gives:
- dir:///var/backup/test => /var/backup/test
- dir://var/backup/test => /backup/test

I would expect the first one to be good, `/var/backup/test`, yes?

Originally, the error I encountered was during borgbackup's repository initialisation:
```
TASK [borg-backup : Initialise the repository, to test access and retrieve the key] *********************************************************
task path: /home/frederic/Documents/code/homebox/install/playbooks/roles/borg-backup/tasks/main.yml:149
changed: [homebox] => (item={'name': 'local', 'url': 'dir://var/backups/homebox', 'active': True, 'frequency': 'daily', 'keep_daily': 3, 'compression': 'lz4'}) => changed=true 
  cmd: /usr/local/sbin/homebox-backup --action init --config local --import-key-path /tmp/backup-keys-import/local.key --export-key-path /tmp/backup-keys-export/local.key
  delta: '0:00:01.497448'
  end: '2019-08-10 19:49:03.776765'
  invocation:
    module_args:
      _raw_params: /usr/local/sbin/homebox-backup --action init --config local --import-key-path /tmp/backup-keys-import/local.key --export-key-path /tmp/backup-keys-export/local.key
      _uses_shell: true
      argv: null
      chdir: null
      creates: null
      executable: null
      removes: null
      stdin: null
      warn: true
  location:
    active: true
    compression: lz4
    frequency: daily
    keep_daily: 3
    name: local
    url: dir://var/backups/homebox
  rc: 0
  start: '2019-08-10 19:49:02.279317'
  stderr: |-
    --- Logging error ---
    Traceback (most recent call last):
      File "/usr/local/sbin/homebox-backup", line 703, in main
        manager.initRepository(args.importKeyPath, args.exportKeyPath)
      File "/usr/local/sbin/homebox-backup", line 242, in initRepository
        raise RuntimeError(status.stderr)
    RuntimeError: The parent path of the repo directory [/backups/homebox] does not exist.
  
  
    During handling of the above exception, another exception occurred:
  
    Traceback (most recent call last):
      File "/usr/lib/python3.5/logging/__init__.py", line 981, in emit
        msg = self.format(record)
      File "/usr/lib/python3.5/logging/__init__.py", line 831, in format
        return fmt.format(record)
      File "/usr/lib/python3.5/logging/__init__.py", line 568, in format
        record.message = record.getMessage()
      File "/usr/lib/python3.5/logging/__init__.py", line 331, in getMessage
        msg = msg % self.args
    TypeError: not all arguments converted during string formatting
    Call stack:
      File "/usr/local/sbin/homebox-backup", line 855, in <module>
        main(args)
      File "/usr/local/sbin/homebox-backup", line 741, in main
        logging.error("Exception on running backup: ", str(error))
    Message: 'Exception on running backup: '
    Arguments: ('The parent path of the repo directory [/backups/homebox] does not exist.\n',)
  stderr_lines:
  - '--- Logging error ---'
  - 'Traceback (most recent call last):'
  - '  File "/usr/local/sbin/homebox-backup", line 703, in main'
  - '    manager.initRepository(args.importKeyPath, args.exportKeyPath)'
  - '  File "/usr/local/sbin/homebox-backup", line 242, in initRepository'
  - '    raise RuntimeError(status.stderr)'
  - 'RuntimeError: The parent path of the repo directory [/backups/homebox] does not exist.'
  - ''
  - ''
  - 'During handling of the above exception, another exception occurred:'
  - ''
  - 'Traceback (most recent call last):'
  - '  File "/usr/lib/python3.5/logging/__init__.py", line 981, in emit'
  - '    msg = self.format(record)'
  - '  File "/usr/lib/python3.5/logging/__init__.py", line 831, in format'
  - '    return fmt.format(record)'
  - '  File "/usr/lib/python3.5/logging/__init__.py", line 568, in format'
  - '    record.message = record.getMessage()'
  - '  File "/usr/lib/python3.5/logging/__init__.py", line 331, in getMessage'
  - '    msg = msg % self.args'
  - 'TypeError: not all arguments converted during string formatting'
  - 'Call stack:'
  - '  File "/usr/local/sbin/homebox-backup", line 855, in <module>'
  - '    main(args)'
  - '  File "/usr/local/sbin/homebox-backup", line 741, in main'
  - '    logging.error("Exception on running backup: ", str(error))'
  - 'Message: ''Exception on running backup: '''
  - 'Arguments: (''The parent path of the repo directory [/backups/homebox] does not exist.\n'',)'
  stdout: ''
  stdout_lines: <omitted>
```
In the `/usr/local/bin/homebox-backup` (`backup.py`), the `dir://` is also stripped. With a `dir:///var/backups/homebox` location, the initialisation is ok at `/var/backups/homebox`.

I guess the same Python library `urllib` is used in both cases.

**Comment by fredericmoulins** [comment]
I am reopeining this one about dir:// urls with an additional commit concerning backup files exclusion, to use the `urlsplit` filter to get the path to exclude.

**Comment by arodier** [comment]
Yes, this is one is simple, I am still reading the other ones ;-)

**Pull request merged**
